//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeDropper.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeDropper.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        public static string About_application {
            get {
                return ResourceManager.GetString("About_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeDropper is a lightweight Windows color-picking tool that lets you sample any pixel on your screen and instantly copy its value in one of nine formats—HTML, Hex, Delphi Hex, VB Hex, RGB, RGB Float, HSV, HSL or Long. It offers configurable precision, a global hotkey, optional launch-on-startup, and light/dark or system-default themes, making seamless color selection and integration into any design or development workflow effortless..
        /// </summary>
        public static string About_application_description {
            get {
                return ResourceManager.GetString("About_application_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Color Picker.
        /// </summary>
        public static string Advance_Color_Picker {
            get {
                return ResourceManager.GetString("Advance_Color_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already running. Click to start!.
        /// </summary>
        public static string Application_already_running_message {
            get {
                return ResourceManager.GetString("Application_already_running_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application running. Click to start!.
        /// </summary>
        public static string Application_running_message {
            get {
                return ResourceManager.GetString("Application_running_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Check_for_updates {
            get {
                return ResourceManager.GetString("Check_for_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        public static string Color_Code {
            get {
                return ResourceManager.GetString("Color_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Copy_to_Clipboard {
            get {
                return ResourceManager.GetString("Copy_to_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string Dark_Theme {
            get {
                return ResourceManager.GetString("Dark_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delphi Hex.
        /// </summary>
        public static string Delphi_Hex {
            get {
                return ResourceManager.GetString("Delphi_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        public static string Exception_message {
            get {
                return ResourceManager.GetString("Exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye dropper.
        /// </summary>
        public static string Eye_dropper {
            get {
                return ResourceManager.GetString("Eye_dropper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Dropper Options.
        /// </summary>
        public static string Eye_Dropper_Options {
            get {
                return ResourceManager.GetString("Eye_Dropper_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Hex {
            get {
                return ResourceManager.GetString("Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSL.
        /// </summary>
        public static string HSL {
            get {
                return ResourceManager.GetString("HSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSV.
        /// </summary>
        public static string HSV {
            get {
                return ResourceManager.GetString("HSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch On Startup.
        /// </summary>
        public static string Launch_On_Startup {
            get {
                return ResourceManager.GetString("Launch_On_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Float.
        /// </summary>
        public static string RGB_Float {
            get {
                return ResourceManager.GetString("RGB_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string Stack_Trace {
            get {
                return ResourceManager.GetString("Stack_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string Unhandled_exception {
            get {
                return ResourceManager.GetString("Unhandled_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VB Hex.
        /// </summary>
        public static string VB_Hex {
            get {
                return ResourceManager.GetString("VB_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version_xx {
            get {
                return ResourceManager.GetString("Version_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Default.
        /// </summary>
        public static string Windows_default {
            get {
                return ResourceManager.GetString("Windows_default", resourceCulture);
            }
        }
    }
}
