//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeDropper.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeDropper.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Privileges Required.
        /// </summary>
        public static string Administrative_privileges_required {
            get {
                return ResourceManager.GetString("Administrative_privileges_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting &apos;Install&apos;, you agree to terms of use..
        /// </summary>
        public static string Agree_terms {
            get {
                return ResourceManager.GetString("Agree_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of the EyeDropper setup is already running..
        /// </summary>
        public static string Another_instance_of_the_EyeDropper_setup_is_already_running {
            get {
                return ResourceManager.GetString("Another_instance_of_the_EyeDropper_setup_is_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been installed successfully. You can now launch the app..
        /// </summary>
        public static string Application_installed_successfully_message {
            get {
                return ResourceManager.GetString("Application_installed_successfully_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any progress you’ve made will be lost if you exit now and you’ll need to start the process again to set up EyeDropper..
        /// </summary>
        public static string Cancel_installation_message {
            get {
                return ResourceManager.GetString("Cancel_installation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel installation.
        /// </summary>
        public static string Cancel_installation_title {
            get {
                return ResourceManager.GetString("Cancel_installation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uninstallation will be canceled and leave EyeDropper installed on your machine..
        /// </summary>
        public static string Cancel_uninstallation_message {
            get {
                return ResourceManager.GetString("Cancel_uninstallation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel uninstallation.
        /// </summary>
        public static string Cancel_uninstallation_title {
            get {
                return ResourceManager.GetString("Cancel_uninstallation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Desktop shortcut.
        /// </summary>
        public static string Create_a_desktop_shortcut {
            get {
                return ResourceManager.GetString("Create_a_desktop_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Start Menu shortcut.
        /// </summary>
        public static string Create_a_start_menu_shortcut {
            get {
                return ResourceManager.GetString("Create_a_start_menu_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissmis.
        /// </summary>
        public static string Dissmis {
            get {
                return ResourceManager.GetString("Dissmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Version: {0}.
        /// </summary>
        public static string Existing_version_xx {
            get {
                return ResourceManager.GetString("Existing_version_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeDropper uninstallation canceled.
        /// </summary>
        public static string Eye_dropper_uninstallation_canceled {
            get {
                return ResourceManager.GetString("Eye_dropper_uninstallation_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeDropper was uninstalled.
        /// </summary>
        public static string Eye_dropper_was_uninstalled {
            get {
                return ResourceManager.GetString("Eye_dropper_was_uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeDropper Installer.
        /// </summary>
        public static string EyeDropper_Installer {
            get {
                return ResourceManager.GetString("EyeDropper_Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Screen Color Picker: Quickly select any color from your screen with a simple click, and get the exact color values you need..
        /// </summary>
        public static string Feature_1 {
            get {
                return ResourceManager.GetString("Feature_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Advanced Color Picker: Refine your color choices using the comprehensive color adjustment panel. Customize your selection with various color modes, including RGB, HSL, CMYK, and Hex values..
        /// </summary>
        public static string Feature_2 {
            get {
                return ResourceManager.GetString("Feature_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With EyeDropper, you can streamline your workflow and make color decisions confidently. Let’s get started!.
        /// </summary>
        public static string Final_note {
            get {
                return ResourceManager.GetString("Final_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Please retry installing and give the required permissions when prompted.
        ///If you are not able to give admin privileges to the installer, please contact your system administrator for help..
        /// </summary>
        public static string Generic_elevate_error_message {
            get {
                return ResourceManager.GetString("Generic_elevate_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeDropper couldn’t complete the installation due to an unexpected error. Click “Logs” below to see more details, then try running the installer again. If you continue to have trouble, please reach out to our support team at support@pixelprodigy.com..
        /// </summary>
        public static string Generic_error_message {
            get {
                return ResourceManager.GetString("Generic_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it’s your first install, nothing related to EyeDropper installed will remain on your computer..
        /// </summary>
        public static string Install_canceled_first_install_message {
            get {
                return ResourceManager.GetString("Install_canceled_first_install_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ‘Install’ if you change your mind..
        /// </summary>
        public static string Install_canceled_select_install_message {
            get {
                return ResourceManager.GetString("Install_canceled_select_install_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are upgrading, EyeDropper will remain and only the upgrade changes will be canceled and removed..
        /// </summary>
        public static string Install_canceled_upgrade_message {
            get {
                return ResourceManager.GetString("Install_canceled_upgrade_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install to.
        /// </summary>
        public static string Install_to {
            get {
                return ResourceManager.GetString("Install_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation canceled.
        /// </summary>
        public static string Installation_canceled {
            get {
                return ResourceManager.GetString("Installation_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Complete!.
        /// </summary>
        public static string Installation_complete {
            get {
                return ResourceManager.GetString("Installation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation details.
        /// </summary>
        public static string Installation_details {
            get {
                return ResourceManager.GetString("Installation_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Failed.
        /// </summary>
        public static string Installation_failed {
            get {
                return ResourceManager.GetString("Installation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        public static string Installation_successful {
            get {
                return ResourceManager.GetString("Installation_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing application.
        /// </summary>
        public static string Installing_application {
            get {
                return ResourceManager.GetString("Installing_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Features:.
        /// </summary>
        public static string Key_features_header {
            get {
                return ResourceManager.GetString("Key_features_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanch on startup.
        /// </summary>
        public static string Lanch_on_startup {
            get {
                return ResourceManager.GetString("Lanch_on_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch App.
        /// </summary>
        public static string Launch_app {
            get {
                return ResourceManager.GetString("Launch_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string Privacy_statement {
            get {
                return ResourceManager.GetString("Privacy_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress tracker.
        /// </summary>
        public static string Progress_tracker {
            get {
                return ResourceManager.GetString("Progress_tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Installation Folder.
        /// </summary>
        public static string Select_installation_folder {
            get {
                return ResourceManager.GetString("Select_installation_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during setup..
        /// </summary>
        public static string Something_went_wrong_during_setup {
            get {
                return ResourceManager.GetString("Something_went_wrong_during_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all set up and ready to start using EyeDropper!.
        /// </summary>
        public static string Start_using_eye_dropper_message {
            get {
                return ResourceManager.GetString("Start_using_eye_dropper_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully uninstalled all packages and components related to the EyeDropper from your computer..
        /// </summary>
        public static string Successully_uninstalled_message {
            get {
                return ResourceManager.GetString("Successully_uninstalled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • The installation requires administrative privileges to make changes to your computer..
        /// </summary>
        public static string The_installation_requires_administrative_privileges_to_make_changes_to_your_computer {
            get {
                return ResourceManager.GetString("The_installation_requires_administrative_privileges_to_make_changes_to_your_compu" +
                        "ter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest version of EyeDropper have already been installed..
        /// </summary>
        public static string The_latest_version_of_eye_dropper_have_already_been_installed {
            get {
                return ResourceManager.GetString("The_latest_version_of_eye_dropper_have_already_been_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uninstallation has been canceled..
        /// </summary>
        public static string The_uninstallation_has_been_canceled {
            get {
                return ResourceManager.GetString("The_uninstallation_has_been_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a problem installing.
        /// </summary>
        public static string There_s_a_problem_installing {
            get {
                return ResourceManager.GetString("There_s_a_problem_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall EyeDropper application.
        /// </summary>
        public static string Uninstall_EyeDropper_application {
            get {
                return ResourceManager.GetString("Uninstall_EyeDropper_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling application.
        /// </summary>
        public static string Uninstalling_application {
            get {
                return ResourceManager.GetString("Uninstalling_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling the EyeDropper will remove all related packages and components from your computer..
        /// </summary>
        public static string Uninstalling_message {
            get {
                return ResourceManager.GetString("Uninstalling_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version_xx {
            get {
                return ResourceManager.GetString("Version_xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Logs.
        /// </summary>
        public static string View_logs {
            get {
                return ResourceManager.GetString("View_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeDropper is a versatile tool designed to help you easily capture and identify colors directly from your screen. Whether you&apos;re a designer, developer, or artist, EyeDropper is your perfect companion for precise color selection..
        /// </summary>
        public static string Welcome_description {
            get {
                return ResourceManager.GetString("Welcome_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install EyeDropper application.
        /// </summary>
        public static string Welcome_page_title {
            get {
                return ResourceManager.GetString("Welcome_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EyeDropper Installer.
        /// </summary>
        public static string Welcome_title {
            get {
                return ResourceManager.GetString("Welcome_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add components.
        /// </summary>
        public static string WelcomePage_AddComponentsButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_AddComponentsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string WelcomePage_InstallButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an offline installer.
        /// </summary>
        public static string WelcomePage_LayoutButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_LayoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string WelcomePage_RepairButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_RepairButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string WelcomePage_UninstallButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_UninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string WelcomePage_UpdateButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the graphical installer for {0}!.
        /// </summary>
        public static string WelcomePage_WelcomeText {
            get {
                return ResourceManager.GetString("WelcomePage_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your&apos;re good to go.
        /// </summary>
        public static string Your_re_good_to_go {
            get {
                return ResourceManager.GetString("Your_re_good_to_go", resourceCulture);
            }
        }
    }
}
